server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:

          ##################################################
          # 1) GLOBAL CORS (for your React frontend)
          ##################################################
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:5173"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                allow-credentials: true

          ##################################################
          # 2) ROUTES
          ##################################################
          routes:

            # ----------------------------------------------
            # 2.1 Notification microservice (REST)
            # ----------------------------------------------
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/notifications/**
              filters:
                - StripPrefix=1
                - JwtUserFilter

            # ----------------------------------------------
            # 2.2 Monolith backend
            # ----------------------------------------------
            - id: campusTalk-monolith
              uri: http://localhost:8082
              predicates:
                - Path=/api/**, /auth/**, /clubs/**, /events/**, /posts/**

            # ----------------------------------------------
            # 2.3 WebSocket notifications (WS Gateway)
            # ----------------------------------------------
            - id: notification-ws-gateway
              uri: lb:ws://notification-ws-gateway
              predicates:
                - Path=/ws/**
              filters:
                - StripPrefix=0

jwt:
  secret: "super-secret-key-change-me"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env"

