server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      # 1️⃣ ENABLE WebSocket Proxying
      httpclient:
        websocket:
          max-frame-payload-length: 65536
          max-frame-size: 65536

      # 2️⃣ KEEP HOST HEADER (CRITICAL FOR WS HANDSHAKE)
      default-filters:
        - PreserveHostHeader

      # 3️⃣ CORS (REST + WEBSOCKET)
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"   # React
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true

      # 4️⃣ ROUTES
      routes:

        # ---------------------------------------
        # REST → NOTIFICATION-SERVICE
        # ---------------------------------------
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            - JwtUserFilter

        # ---------------------------------------
        # REST → Monolithic main backend
        # ---------------------------------------
        - id: campusTalk-monolith
          uri: lb://CAMPUSTALK
          predicates:
            - Path=/api/**, /auth/**, /clubs/**, /events/**, /posts/**

        # ---------------------------------------
        # WEBSOCKET → NOTIFICATION-WS-GATEWAY
        # ---------------------------------------
        - id: notification-ws-gateway
          uri: lb:ws://NOTIFICATION-WS-GATEWAY
          predicates:
            - Path=/ws/**
          filters:
            - JwtUserFilter


# JWT Secret
jwt:
  secret: supersecretkeyforjwtsigning123456789012345

# Eureka Discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
