server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:

          # 1️⃣ Keep Host header (required for WS handshake)
          default-filters:
            - PreserveHostHeader

          # 2️⃣ WebSocket Support
          httpclient:
            websocket:
              max-frame-payload-length: 65536
              max-frame-size: 65536

          # 3️⃣ CORS
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:5173"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                allow-credentials: true

          # 4️⃣ ROUTES (NEW KEY!)
          routes:

            # REST Notification Service
            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/notifications/**
              filters:
                - StripPrefix=1
                - JwtUserFilter

            # Main monolith backend
            - id: campusTalk-monolith
              uri: lb://CAMPUSTALK
              predicates:
                - Path=/api/**, /auth/**, /clubs/**, /events/**, /posts/**

            # Notification WebSocket Gateway (WS)
            - id: notification-ws-gateway
              uri: lb:ws://NOTIFICATION-WS-GATEWAY
              predicates:
                - Path=/ws
              filters:
                - JwtUserFilter


jwt:
  secret: supersecretkeyforjwtsigning123456789012345

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
