server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:5173"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                allow-credentials: true

      routes:

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
            - JwtUserFilter

        - id: campusTalk-monolith
          uri: http://localhost:8081
          predicates:
            - Path=/api/**, /auth/**, /clubs/**, /events/**, /posts/**

        - id: notification-ws-gateway
          uri: lb:ws://notification-ws-gateway
          predicates:
            - Path=/ws/**
          filters: []   # IMPORTANT → no StripPrefix for WebSockets

jwt:
  secret: supersecretkeyforjwtsigning123456789012345

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env"
