server:
  port: 8085

spring:
  application:
    name: NOTIFICATION-GATEWAY

rabbitmq:
  host: localhost
  port: 5672s
  autoupdate: true
  username: guest
  password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false

