spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://${NOTIF_DB_HOST:localhost}:${NOTIF_DB_PORT:5432}/${NOTIF_DB_NAME:employeedb}
    username: ${NOTIF_DB_USER:employeedbuser}
    password: ${NOTIF_DB_PASS:0000}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER:http://localhost:8888}

server:
  port: ${PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

