server:
  port: 8085

spring:
  application:
    name: NOTIFICATION-WS-GATEWAY

  main:
    web-application-type: reactive  # REQUIRED for Reactor Netty WebFlux

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
